### ISSUE TITLE
Punto 1 

### ISSUE THREAD

**Issue by KarolBurbanoN** [KarolBurbanoN/MiniProyecto-2-POE#1]
Realizar una interfaz gráfica que cumpla con los siguientes requerimientos:

**1. Diseño de la interfaz de usuario:** Creación de una interfaz intuitiva y fácil de usar que muestre el inventario de productos de la ferretería.

**2. Visualización de inventario:** Implementación de funciones para mostrar la lista de productos disponibles, incluyendo su nombre, descripción, precio y cantidad en stock.

**3.** Si hago click encima de un producto, debe mostrarse una ventana donde además de los 4 campos de los productos anteriormente mencionados, muestre material de elaboración, ejemplos de uso y que herramienta se necesita para poder usarse.

**4. Adición de productos:** Desarrollo de funciones que permitan agregar nuevos productos al inventario, especificando su nombre, descripción, precio y cantidad inicial.

**5. Eliminación de productos:** Implementación de opciones para eliminar productos del inventario cuando sea necesario.

**6. Actualización de inventario:** Desarrollo de funcionalidades que permitan actualizar la cantidad de productos disponibles en el inventario, como la venta de productos o la recepción de nuevos suministros.

**7.** Al presionar un botón, se deben mostrar las siguientes estadísticas:
a. El precio total de todos los productos en inventario (precio por cantidad de todos los productos)
b. Cuales son los 2 productos con más stock y los 2 que menos stock tienen
c. ¿Cuáles son las herramientas que más se usan para los productos?

No hacer nada por consola, todo debe ser por interfaz gráfica. Desde pedir la info hasta mostrarla

**Comment by VeronicaMujica** [comment]
Punto 1 realizado en su totalidad haciendo uso de la herramienta Netbeans a su vez.

**Comment by JeidyMurillo** [comment]
Se completo el programa con sus especificaciones
